version: "1.0"

services:
  # jupyterlab with pyspark
  pyspark:
    image: jupyter/pyspark-notebook:latest
    restart: unless-stopped
    container_name: jupyter_notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=iambatman
    ports:
      - "9999:8888"
    volumes:
      - /home/pi/Documents/jupyter_notebook:/home/jovyan/work
