services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - RUN_OPTS= #optional
    volumes:
      - /home/pi/Documents/tvheadend/config:/config
      - /home/pi/Videos/Recordings:/recordings
    network_mode: host
    restart: unless-stopped
